# Generated by Django 4.2.16 on 2024-11-13 11:19

from django.db import migrations, models
import share.models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='key',
            field=models.CharField(default=share.models.generate_unique_key, max_length=5, unique=True),
        ),
    ]
